name: clean_code
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.26.0
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
